[package]
name = "ds-polars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.26.1"
smartcore = "0.3.0"
polars-core = {version = "0.26.1", features=["ndarray"]}