[package]
name = "polars-smartcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.1"
ndarray = "0.15.6"
polars = { version = "0.26.1", features=["ndarray"]}

smartcore = "0.3.0"
